server:
  port: 0

spring:
  application:
    name: catalogservice
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    config:
      enabled: true
      name: catalogservice
      fail-fast: true
      retry:
        max-attempts: 5
        initial-interval: 1000
        multiplier: 1.1
      request-connect-timeout: 2000
      request-read-timeout: 2000

  profiles:
    active: dev


eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:8765/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}


## logging ??
logging:
  level:
    com.example.catalog: DEBUG

## spring boot actuator ??
management:
  endpoints:
    web:
      exposure:
        include: busrefresh





